Repository astrolabsoftware/fink-tutorials, pull requests merged in 2021-07, with the labels that each got.

#17 Update with the broker workshop materials
  .gitignore
  MMA/MMA.ipynb
  extragalactic/extragalactic.ipynb
  galactic/galactic.ipynb
  interfaces/README.md
  interfaces/infrastructure.png
  interfaces/search.png
  interfaces/skymap.png
  interfaces/sn_view.png
  interfaces/view.png
  requirements.txt
  sso/sso.ipynb
Labels: enhancement

#19 Singularity container
  Singularity
Labels: enhancement, singularity

#20 Update README with singularity steps
  README.md
Labels: documentation, singularity
